version: '3.9'

services:
  fine-tuning-llm-qlora:
    container_name: fine-tuning-llm-qlora
    hostname: fine-tuing-llm-qlora
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        FTP_PROXY: ${FTP_PROXY:-}
        NO_PROXY: ${NO_PROXY:-}
        http_proxy: ${HTTP_PROXY:-}
        https_proxy: ${HTTPS_PROXY:-}
        ftp_proxy: ${FTP_PROXY:-}
        no_proxy: ${NO_PROXY:-}
    environment:
      HTPP_PROXY: ${HTPP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      FTP_PROXY: ${FTP_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
      http_proxy: ${HTTP_PROXY:-}
      https_proxy: ${HTTPS_PROXY:-}
      ftp_proxy: ${FTP_PROXY:-}
      no_proxy: ${NO_PROXY:-}
    working_dir: /teramatsu/qlora
    volumes:
      - ./:/teramatsu/qlora
    tty: true
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: '10m'
